from abc import ABC, abstractmethod
from typing import Any

class VectorStoreAdapter(ABC):
    @abstractmethod
    def add_session_summary(self, session_id: str, summary: str) -> None: ...
    @abstractmethod
    def add_knowledge_node(self, node_id: str, title: str, text: str) -> None: ...
    @abstractmethod
    def add_page_text(self, url: str, title: str, text: str, ts: float | None = None, headings: list[str] | None = None) -> int: ...
    @abstractmethod
    def add_doc_text(self, doc_path: str, doc_name: str, item_kind: str, item_index: int, item_label: str, text: str, ts: float | None = None, app: str = "") -> int: ...
    @abstractmethod
    def search(self, query: str, top_k: int = 10, types: list[str] | None = None) -> list[dict]: ...
    @abstractmethod
    def count(self) -> int: ...

class TimelineDBAdapter(ABC):
    @abstractmethod
    async def insert_event(self, event: Any) -> None: ...
    @abstractmethod
    async def insert_events_bulk(self, events: list[Any]) -> None: ...
    @abstractmethod
    async def assign_session(self, event_id: str, session_id: str) -> None: ...
    @abstractmethod
    async def upsert_session(self, session: Any) -> None: ...
    @abstractmethod
    async def save_analysis(self, analysis: Any) -> None: ...
    # ... (other methods needed by the system)
    @abstractmethod
    async def close(self) -> None: ...

class BlobStoreAdapter(ABC):
    @abstractmethod
    def upload(self, key: str, data: bytes) -> None: ...
    @abstractmethod
    def download(self, key: str) -> bytes: ...
    @abstractmethod
    def delete(self, key: str) -> None: ...
