"""Codegen: manifest → typed event vocabulary for client (TS) and server (Py).

`capman web codegen <manifest>` emits the TypeScript event-name union + prop
types and the matching Python Literals from the SAME manifest, so the client
SDK and the collector cannot drift.
"""
from __future__ import annotations

from capman.web.friction import FRICTION_EVENTS
from capman.web.manifest import ProductManifest, PropSpec, load_manifest

_HEADER_TS = "// Generated by `capman web codegen` from manifest '{key}' — do not edit by hand.\n"
_HEADER_PY = "# Generated by `capman web codegen` from manifest '{key}' — do not edit by hand.\n"


def _ts_prop_type(spec: PropSpec) -> str:
    if spec.type == "enum":
        return " | ".join(f'"{v}"' for v in (spec.values or []))
    if spec.type in ("int", "bucket"):
        return "number"
    if spec.type == "bool":
        return "boolean"
    return "string"


def _py_prop_type(spec: PropSpec) -> str:
    if spec.type == "enum":
        return "Literal[" + ", ".join(f'"{v}"' for v in (spec.values or [])) + "]"
    if spec.type in ("int", "bucket"):
        # bucket props are sent as numbers; the collector stores the label
        return "int" if spec.type == "int" else "float"
    if spec.type == "bool":
        return "bool"
    return "str"


def generate_ts(manifest: ProductManifest) -> str:
    lines = [_HEADER_TS.format(key=manifest.key)]

    all_names = list(manifest.events) + list(FRICTION_EVENTS)
    lines.append("export type CwEventName =")
    lines.extend(f'  | "{name}"' for name in all_names)
    lines.append(";")
    lines.append("")

    lines.append("export interface CwEventProps {")
    for name, spec in manifest.events.items():
        props = ", ".join(
            f"{p}{'?' if ps.optional else ''}: {_ts_prop_type(ps)}"
            for p, ps in spec.props.items()
        )
        lines.append(f"  {name}: {{ {props} }};")
    for name, props_spec in FRICTION_EVENTS.items():
        rendered = ", ".join(
            f"{p}{'?' if ps.optional else ''}: {_ts_prop_type(ps)}"
            for p, ps in props_spec.items()
        )
        lines.append(f"  {name}: {{ {rendered} }};")
    lines.append("}")
    lines.append("")

    lines.append("export const CW_STEPS: Record<string, string> = {")
    for name, spec in manifest.events.items():
        if spec.step:
            lines.append(f'  "{name}": "{spec.step}",')
    lines.append("};")
    lines.append("")

    order = ", ".join(f'"{s}"' for s in manifest.steps)
    lines.append(f"export const CW_STEP_ORDER: string[] = [{order}];")
    lines.append("")
    return "\n".join(lines)


def generate_py(manifest: ProductManifest) -> str:
    lines = [_HEADER_PY.format(key=manifest.key), "from typing import Literal", ""]

    all_names = list(manifest.events) + list(FRICTION_EVENTS)
    quoted = ", ".join(f'"{n}"' for n in all_names)
    lines.append(f"EventName = Literal[{quoted}]")
    lines.append("")
    lines.append(f"EVENT_NAMES: tuple[str, ...] = ({quoted})")
    lines.append("")

    lines.append("EVENT_STEPS: dict[str, str] = {")
    for name, spec in manifest.events.items():
        if spec.step:
            lines.append(f'    "{name}": "{spec.step}",')
    lines.append("}")
    lines.append("")

    lines.append("EVENT_PROPS: dict[str, dict[str, str]] = {")
    for name, spec in manifest.events.items():
        props = ", ".join(f'"{p}": \'{_py_prop_type(ps)}\'' for p, ps in spec.props.items())
        lines.append(f'    "{name}": {{ {props} }},')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def codegen(manifest_path: str, lang: str = "ts") -> str:
    manifest = load_manifest(manifest_path)
    if lang == "ts":
        return generate_ts(manifest)
    if lang == "py":
        return generate_py(manifest)
    raise ValueError(f"unknown lang '{lang}' (expected 'ts' or 'py')")
