"""Codegen golden tests — TS and Python outputs from one manifest."""
from __future__ import annotations

import textwrap
from pathlib import Path

import pytest

from capman.web.codegen import codegen, generate_py, generate_ts
from capman.web.manifest import load_manifest

MANIFEST_TOML = """
[product]
key = "acme"
description = "A generic widget product."

[steps]
order = ["land", "edit", "done"]

[[events]]
name = "page_view"
step = "land"

[[events]]
name = "widget_click"
step = "edit"
props = { target = { type = "enum", values = ["save", "cancel"] }, n = { type = "int", max = 20 } }

[[events]]
name = "export_result"
step = "done"
props = { ok = { type = "bool", optional = false }, size = { type = "bucket", buckets = [1.0, 5.0, 10.0] } }
"""


@pytest.fixture()
def manifest(tmp_path: Path):
    p = tmp_path / "acme.toml"
    p.write_text(textwrap.dedent(MANIFEST_TOML))
    return load_manifest(p)


class TestGenerateTs:
    def test_event_name_union_includes_declared_and_reserved(self, manifest):
        ts = generate_ts(manifest)
        assert '| "page_view"' in ts
        assert '| "widget_click"' in ts
        assert '| "rage_click"' in ts
        assert '| "time_to_first_action"' in ts

    def test_enum_becomes_literal_union(self, manifest):
        ts = generate_ts(manifest)
        assert 'target?: "save" | "cancel"' in ts

    def test_required_props_not_optional(self, manifest):
        ts = generate_ts(manifest)
        assert "ok: boolean" in ts
        assert "ok?: boolean" not in ts

    def test_numeric_types(self, manifest):
        ts = generate_ts(manifest)
        assert "n?: number" in ts
        assert "size?: number" in ts

    def test_steps_map_and_order(self, manifest):
        ts = generate_ts(manifest)
        assert '"page_view": "land"' in ts
        assert 'export const CW_STEP_ORDER: string[] = ["land", "edit", "done"];' in ts

    def test_header_marks_generated(self, manifest):
        assert generate_ts(manifest).startswith("// Generated by `capman web codegen`")


class TestGeneratePy:
    def test_literal_includes_all_names(self, manifest):
        py = generate_py(manifest)
        assert 'EventName = Literal["page_view", "widget_click", "export_result"' in py
        assert '"rage_click"' in py

    def test_prop_types(self, manifest):
        py = generate_py(manifest)
        assert '"target": \'Literal["save", "cancel"]\'' in py
        assert '"ok": \'bool\'' in py
        assert '"n": \'int\'' in py
        assert '"size": \'float\'' in py

    def test_steps_map(self, manifest):
        py = generate_py(manifest)
        assert '"page_view": "land"' in py

    def test_generated_py_is_valid_syntax(self, manifest):
        compile(generate_py(manifest), "<codegen>", "exec")


class TestCodegenEntry:
    def test_lang_selection(self, tmp_path, manifest):
        p = tmp_path / "acme.toml"
        assert codegen(str(p), lang="ts").startswith("// Generated")
        assert codegen(str(p), lang="py").startswith("# Generated")

    def test_unknown_lang(self, tmp_path):
        p = tmp_path / "acme.toml"
        p.write_text(textwrap.dedent(MANIFEST_TOML))
        with pytest.raises(ValueError, match="unknown lang"):
            codegen(str(p), lang="rust")

    def test_no_product_nouns_leak_into_reserved_section(self, manifest):
        ts = generate_ts(manifest)
        reserved_block = ts.split("export interface CwEventProps")[1]
        assert "acme" not in reserved_block.split("CW_STEPS")[0].replace("widget_click", "").replace("export_result", "")
