"""Unit tests for AISessionSensor: transcript parsing, noise filtering, offsets."""
import asyncio
import json
import sqlite3
import time

import pytest

from capman.events import EventType
from capman.sensors.ai_sessions import (
    AISessionSensor, _flatten_content, _has_tool_result, _hermes_label,
    _is_noise, _parse_iso,
)


def _sensor(cfg=None):
    return AISessionSensor(config={"sensors": {"ai_sessions": cfg or {}}}, queue=asyncio.Queue())


async def _drain(s):
    out = []
    while not s._queue.empty():
        out.append(s._queue.get_nowait())
    return out


# --- pure helpers ---------------------------------------------------------

def test_flatten_content_text_only():
    assert _flatten_content("  hi  ") == "hi"
    blocks = [
        {"type": "text", "text": "hello"},
        {"type": "tool_use", "name": "Bash", "input": {}},
        {"type": "text", "text": "world"},
    ]
    assert _flatten_content(blocks) == "hello\nworld"


def test_flatten_content_drops_tool_result():
    assert _flatten_content([{"type": "tool_result", "content": "stdout dump"}]) == ""


def test_has_tool_result():
    assert _has_tool_result([{"type": "tool_result", "content": "x"}])
    assert _has_tool_result([{"type": "tool_use", "name": "Read"}])
    assert not _has_tool_result([{"type": "text", "text": "hi"}])
    assert not _has_tool_result("plain string")


def test_is_noise():
    assert _is_noise("<command-name>ls</command-name>")
    assert _is_noise("Caveat: The messages below were generated by ...")
    assert _is_noise("The file /x/y.py has been updated successfully.")
    assert _is_noise("You are hermes-deepseek-flash, an AI agent employee in a ...")
    assert _is_noise("Paperclip runtime identity:\n- Agent ID: abc")
    assert not _is_noise("please fix the scroll bug on the dashboard")


def test_hermes_label():
    assert _hermes_label("Handle Paperclip wake for issue heartbeat", "x") \
        == "Handle Paperclip wake for issue heartbeat"
    assert _hermes_label("You are hermes-deepseek-flash, an AI agent employee ...", "x") \
        == "hermes-deepseek-flash run"
    # ellipsis-truncated title (as Hermes actually stores it)
    assert _hermes_label("You are hermes-deepseek-flash, an AI agent… #2", "x") \
        == "hermes-deepseek-flash run"
    assert _hermes_label("", "paperclip:company:u1:agent:u2") == "paperclip run"
    assert _hermes_label("", "") == "hermes run"


def test_parse_iso():
    assert _parse_iso("2026-09-10T21:59:16.000Z") == pytest.approx(1789077556.0, abs=1)
    assert _parse_iso(None) is None
    assert _parse_iso("not-a-date") is None


# --- Claude Code transcript --------------------------------------------------

def _claude_line(**kw):
    base = {"type": "user", "sessionId": "s1", "cwd": "/root/workspaces/proj",
            "timestamp": "2026-09-10T21:59:16.000Z"}
    base.update(kw)
    return json.dumps(base)


@pytest.mark.asyncio
async def test_claude_user_prompt_becomes_event(tmp_path):
    f = tmp_path / "sess.jsonl"
    f.write_text("\n".join([
        json.dumps({"type": "mode", "sessionId": "s1"}),                       # meta → skip
        _claude_line(message={"role": "user", "content": "fix the login bug"}),
        _claude_line(type="assistant", message={"role": "assistant", "model": "claude-sonnet-5",
                     "content": [{"type": "text", "text": "On it."},
                                 {"type": "tool_use", "name": "Bash", "input": {}}]}),
        # tool result carried on a "user" line → not a human turn
        _claude_line(message={"role": "user", "content": [{"type": "tool_result", "content": "ok"}]}),
        _claude_line(message={"role": "user", "content": "<command-name>git</command-name>"}),
    ]) + "\n")

    s = _sensor({"backfill_hours": 999, "backfill_max_lines": 999})
    await s._consume_file(f, {}, first_pass=True,
                          backfill_cutoff=0, backfill_max_lines=999)
    evs = await _drain(s)

    assert [e.payload["role"] for e in evs] == ["user", "assistant"]
    u, a = evs
    assert u.type == EventType.AI_CONVERSATION
    assert u.app == "claude-code"
    assert u.payload["text"] == "fix the login bug"
    assert u.payload["project"] == "proj"
    assert u.payload["session_id"] == "s1"
    assert a.payload["text"] == "On it."          # tool_use block dropped
    assert a.payload["model"] == "claude-sonnet-5"


@pytest.mark.asyncio
async def test_offset_tracking_only_emits_new_lines(tmp_path):
    f = tmp_path / "sess.jsonl"
    f.write_text(_claude_line(message={"role": "user", "content": "first"}) + "\n")
    s = _sensor()
    pos: dict = {}
    await s._consume_file(f, pos, first_pass=True, backfill_cutoff=0, backfill_max_lines=999)
    assert len(await _drain(s)) == 1

    with f.open("a") as fh:
        fh.write(_claude_line(message={"role": "user", "content": "second"}) + "\n")
    await s._consume_file(f, pos, first_pass=False, backfill_cutoff=0, backfill_max_lines=999)
    evs = await _drain(s)
    assert [e.payload["text"] for e in evs] == ["second"]


@pytest.mark.asyncio
async def test_first_pass_skips_stale_files(tmp_path):
    f = tmp_path / "old.jsonl"
    f.write_text(_claude_line(message={"role": "user", "content": "ancient"}) + "\n")
    import os
    old = time.time() - 10 * 3600
    os.utime(f, (old, old))

    s = _sensor()
    await s._consume_file(f, {}, first_pass=True,
                          backfill_cutoff=time.time() - 3600, backfill_max_lines=999)
    assert await _drain(s) == []


# --- Codex rollout transcript ---------------------------------------------

@pytest.mark.asyncio
async def test_codex_response_items(tmp_path):
    f = tmp_path / "rollout-2026-09-02T21-00-47-01a063ec-a2b3-7af3-bffa-98c8c8605902.jsonl"
    f.write_text("\n".join([
        json.dumps({"type": "session_meta", "payload": {"session_id": "abc123"}}),
        json.dumps({"type": "response_item", "timestamp": "2026-09-02T21:02:34.447Z",
                    "payload": {"type": "message", "role": "developer",
                                "content": [{"type": "input_text", "text": "<skills_instructions>"}]}}),
        json.dumps({"type": "response_item", "timestamp": "2026-09-02T21:02:35.000Z",
                    "payload": {"type": "message", "role": "user",
                                "content": [{"type": "input_text", "text": "make the header sticky"}]}}),
        json.dumps({"type": "response_item", "timestamp": "2026-09-02T21:02:40.000Z",
                    "payload": {"type": "message", "role": "assistant",
                                "content": [{"type": "output_text", "text": "Done."}]}}),
    ]) + "\n")

    s = _sensor()
    await s._consume_file(f, {}, first_pass=True, backfill_cutoff=0, backfill_max_lines=999)
    evs = await _drain(s)
    assert [(e.app, e.payload["role"]) for e in evs] == [("codex", "user"), ("codex", "assistant")]
    assert evs[0].payload["text"] == "make the header sticky"
    assert evs[0].payload["session_id"] == "01a063ec-a2b3-7af3-bffa-98c8c8605902"


# --- Hermes: .hermes_history human prompt log ------------------------------

@pytest.mark.asyncio
async def test_hermes_history_blocks(tmp_path):
    f = tmp_path / ".hermes_history"
    f.write_text(
        "\n# 2026-09-07 08:15:01.123\n+what's the paperclip port\n"
        "\n# 2026-09-07 08:18:44.000\n+replace the header\n+with SHICKO-AGENT\n"
        "\n# 2026-09-07 09:00:00.000\n+You are botx, an AI agent employee somewhere\n"
    )
    s = _sensor()
    await s._consume_file(f, {}, first_pass=True, backfill_cutoff=0, backfill_max_lines=999)
    evs = await _drain(s)
    assert [e.payload["text"] for e in evs] == [
        "what's the paperclip port",
        "replace the header\nwith SHICKO-AGENT",   # multi-line block joined
    ]                                              # bootstrap block filtered as noise
    assert all(e.app == "hermes" and e.payload["role"] == "user" for e in evs)


# --- Hermes: state.db messages ------------------------------------------------

def _hermes_db(tmp_path, rows):
    p = tmp_path / "state.db"
    con = sqlite3.connect(p)
    con.execute("CREATE TABLE sessions (id TEXT PRIMARY KEY, title TEXT, model TEXT, "
                "source TEXT, cwd TEXT, git_branch TEXT)")
    con.execute("CREATE TABLE messages (id INTEGER PRIMARY KEY AUTOINCREMENT, "
                "session_id TEXT, role TEXT, content TEXT, timestamp REAL)")
    con.execute("INSERT INTO sessions VALUES (?,?,?,?,?,?)",
                ("sess-1", "Fix the login bug", "claude-opus-4-7", "api_server", None, None))
    for role, content, ts in rows:
        con.execute("INSERT INTO messages (session_id, role, content, timestamp) VALUES (?,?,?,?)",
                    ("sess-1", role, content, ts))
    con.commit()
    con.close()
    return p


@pytest.mark.asyncio
async def test_hermes_db_forward_only_and_cursor(tmp_path):
    now = time.time()
    db = _hermes_db(tmp_path, [
        ("user", "You are bot, an AI agent employee ...", now - 50),  # noise
        ("assistant", "Looking into the login handler now.", now - 40),
        ("tool", "some stdout", now - 35),                            # role filtered by SQL
        ("assistant", "", now - 30),                                  # empty skipped
        ("assistant", "Nothing to do.", now - 20),                    # heartbeat noise
    ])
    s = _sensor()
    s._hermes_cursor = None
    await s._poll_hermes_db(db, first_pass=True,
                            backfill_cutoff=now - 3600, backfill_max_lines=999)
    evs = await _drain(s)
    assert len(evs) == 1
    e = evs[0]
    assert e.app == "hermes"
    assert e.payload["role"] == "assistant"
    assert e.payload["text"] == "Looking into the login handler now."
    assert e.payload["model"] == "claude-opus-4-7"
    assert e.payload["project"] == "Fix the login bug"
    assert e.window_title == "hermes: Fix the login bug"

    # second poll: nothing new
    await s._poll_hermes_db(db, first_pass=False,
                            backfill_cutoff=now - 3600, backfill_max_lines=999)
    assert await _drain(s) == []

    # a new row arrives → picked up
    con = sqlite3.connect(db)
    con.execute("INSERT INTO messages (session_id, role, content, timestamp) VALUES (?,?,?,?)",
                ("sess-1", "assistant", "Pushed the fix.", time.time()))
    con.commit()
    con.close()
    await s._poll_hermes_db(db, first_pass=False,
                            backfill_cutoff=now - 3600, backfill_max_lines=999)
    evs = await _drain(s)
    assert [e.payload["text"] for e in evs] == ["Pushed the fix."]


@pytest.mark.asyncio
async def test_hermes_db_missing_is_silent(tmp_path):
    s = _sensor()
    s._hermes_cursor = None
    await s._poll_hermes_db(tmp_path / "nope.db", first_pass=True,
                            backfill_cutoff=0, backfill_max_lines=10)
    assert await _drain(s) == []
